POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para falar sobre tecnologia, programação e tudo mais",
  "maximumAtendees": 100
}